fix: random bugs
courtcanva/cc-app pull request #107
Opened 2022-07-05 11:10 UTC by devharris7

2022-07-07 03:16 UTC, tatoMa commented on src/components/EditorSideBar/Blueprints.tsx
> +// import { useGetCourtsQuery, useGetCourtQuery } from "@/pages/api/courtSizeApi";
Steve will move this file into redux/api folder. please becareful of conflicts.

2022-07-07 03:16 UTC, tatoMa commented on src/components/EditorSideBar/Blueprints.tsx
> +        const { img, courtSizeName, courtSizeDetails } = court; // better rename to 'imgUrl'
You can rename them from the source file(../ChangeCourtSize/CourtList) or map them into new names here.

2022-07-07 03:16 UTC, tatoMa commented on src/pages/api/courtSizeApi.ts
> +    baseUrl: "https://uat.api.courtcanva.com/v1", // put into env
0081 card has changed into env. Mind the conflicts.

2022-07-07 03:17 UTC, tatoMa approved these changes

2022-07-07 15:01 UTC, Fuchih requested changes

2022-07-08 06:09 UTC, Fuchih approved these changes

2022-07-08 06:55 UTC, merged