Feature/cc 0014 price bar
courtcanva/cc-app pull request #25
Opened 2022-05-20 04:19 UTC by Fuchih

**open**
![OPEN](https://user-images.githubusercontent.com/51282481/169449452-97716a65-a2c8-4b30-b689-635ad6b2f216.png)

**close**
![close](https://user-images.githubusercontent.com/51282481/169449513-562288de-127d-486c-8778-122e8c036f20.png)

**resposive**
![resposive](https://user-images.githubusercontent.com/51282481/169449548-430b11e2-da5a-4b24-b2c0-4cafdb02f846.png)

**hover**
![Hover](https://user-images.githubusercontent.com/51282481/169449589-8d85102f-9890-418d-af54-af0b064d8442.png)

**active**
![active](https://user-images.githubusercontent.com/51282481/169449608-9df2502f-1602-4c70-b9eb-f30cff1b603a.png)

2022-05-20 05:03 UTC, tatoMa requested changes
Also please double-check with BA and UI designer if this component is the only one showing on the screen with the gray shadow border. Looks like all layout components have different design styles now.
![image](https://user-images.githubusercontent.com/12379895/169454013-ab5547b8-e291-4878-a255-f883acfde869.png)

2022-05-20 05:05 UTC, tatoMa commented on src/components/PriceBar/TireColorBoard.tsx
> +            w="105px"
May need to increase the width of this text component to make the sentence in 2 lines for matching the UI design.

2022-05-20 05:20 UTC, Fuchih commented on src/components/PriceBar/index.tsx
> +              <TireColorBoard />
shold be tile

2022-05-20 06:06 UTC, EmilyGong111 commented
<img width="317" alt="Screen Shot 2022-05-20 at 3 59 45 pm" src="https://user-images.githubusercontent.com/84214439/169463035-289a668a-3c3e-4128-b1df-96ff713ded5a.png">
The Text element has 3 lines, which is different with UI. May need a min-width to keep the sentence in 2 lines.

2022-05-20 06:17 UTC, Fuchih commented
> Also please double-check with BA and UI designer if this component is the only one showing on the screen with the gray shadow border. Looks like all layout components have different design styles now. ![image](https://user-images.githubusercontent.com/12379895/169454013-ab5547b8-e291-4878-a255-f883acfde869.png)

Hi tatoMa:
Yes, according to BA and UI,  it is the only component that has gray shadow border for now
@tatoMa

2022-05-20 09:54 UTC, tatoMa commented on src/components/PriceBar/CourtTemplate.tsx
> +};
It seems like you have 2 components nested with each other in one file. I would recommend to divide them into 2 separate files with passing props through.

2022-05-21 02:11 UTC, tatoMa requested changes
Please change the code to the pic I attached below. This is to fix the animation/transition of the drawer layer higher than footer problem.

2022-05-21 03:16 UTC, tatoMa approved these changes

2022-05-21 03:17 UTC, tatoMa commented
LGTM

2022-05-21 03:18 UTC, Jzeva approved these changes

2022-05-21 03:52 UTC, merged